<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Lobby · animated wave</title>
<style>
/* === ORIGINAL STYLES (unchanged, only reference) === */
:root {
  --background-color: #240008;     
  --text-color: #F5BFCC;            
  --primary-color: #9C344C;         
  --secondary-color: #600B1F;       
  --highlight-color: #D8788F;       
  --border-color: #600B1F;
}

@font-face {
    font-family: mainFont;
    src: url(font/CircularSpotifyText-Medium.otf);
}

*{
    margin: 0;
    padding: 0;
}

/* lobby specific */
.lobby{
  height:100vh;
  display:flex;
  justify-content:center; 
  align-items:center;    
  overflow:hidden;       
  background-color: var(--background-color); /* ensure background */
}
.container{
    display:flex;
    flex-direction:column;
    align-items:center;
    gap:2vh;
}

/* logo wrapper — now hosts both img and SVG ring */
.logo-wrapper {
    position: relative;
    width: 150px;
    height: 150px;
    margin: auto;
}

.logo {
    width: 100%;
    height: 100%;
    border-radius: 50%;
    position: relative;
    z-index: 2;
    display: block;          /* remove extra gap */
}

/* wave-ring SVG – positioned exactly over the image */
.wave-ring {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
    transform-origin: center;
    animation: rotateWave 3s linear infinite;
    pointer-events: none;     /* so clicks go through to burger etc */
}

@keyframes rotateWave {
    from { transform: rotate(0deg); }
    to   { transform: rotate(360deg); }
}

/* wave path styling (filled by js) */
.wave-ring path {
    fill: none;
    stroke: var(--highlight-color);  /* use existing highlight, matches #D8788F */
    stroke-width: 4;
    stroke-linecap: round;
    filter: drop-shadow(0 0 4px var(--highlight-color)); /* gentle glow */
}

/* menu, inputs, buttons – exactly as provided */
h1{
    font-size:4vh;
    font-weight: bold;
    font-family: mainFont;
    color: var(--text-color);
}

input{
    padding:1vh 1vw;
    font-size:2vh;
    width:18vw;
    background-color: var(--secondary-color);
    color: var(--text-color);
    border:0.2vw solid var(--border-color);
    border-radius:0.6vw;
    transition: 0.3s;
}
input::placeholder{
    color: var(--highlight-color);
}
input:focus{
    outline: none; 
    border: 0.2vw solid var(--highlight-color);
    background-color: var(--secondary-color);
    box-shadow: 0 0 1vh var(--highlight-color);
}

button{
    padding:1vh 2vw;
    font-size:2vh;
    background-color: var(--primary-color);
    color: var(--text-color);
    border:none;
    border-radius:0.6vw;
    cursor:pointer;
    transition:0.2s;
}
button:hover{
    background-color: var(--highlight-color);
}

.menu{
    position:absolute;
    top:2vh;
    left:2vw;
}
.burger{
    font-size:3vh;
    cursor:pointer;
    color: var(--text-color);  /* make burger visible */
}
.menu-content{
    display:none;
    flex-direction:column;
    margin-top:1vh;
    background-color: var(--secondary-color);
    border:0.15vw solid var(--border-color);
    border-radius:0.4vw;
}
.menu-content a{
    padding:1vh 1.5vw;
    text-decoration:none;
    color:var(--text-color);
    font-family: mainFont;
}
.menu-content a:hover{
    background-color:var(--primary-color);
}
.menu:hover .menu-content{
    display:flex;
}
</style>
</head>
<body class="lobby">

<!-- Burger Menu (unchanged) -->
<div class="menu">
    <div class="burger">&#9776;</div>
    <div class="menu-content">
        <a href="#">Leave</a>
        <a href="#">Impressum</a>
        <a href="#">More</a>
    </div>
</div>

<!-- Main Content -->
<div class="container">

    <!-- Logo wrapper: image + animated sine ring (now using original JS logic) -->
    <div class="logo-wrapper">
        <!-- original logo image — make sure path exists or replace with placeholder if needed -->
        <img src="img/logoLight.png" class="logo" alt="Logo">

        <!-- SVG wave ring – simplified: only a group/path, no mask or gradient,
             the animated path is generated by script exactly like first snippet -->
        <svg class="wave-ring" viewBox="0 0 240 240">  <!-- Increased from 200x200 -->
        <path id="wavePath" fill="none" stroke="var(--highlight-color)" stroke-width="4"/>
    </svg>
    </div>

    <h1>Join Lobby</h1>

    <input type="text" placeholder="Enter Lobby Code">

    <button>Create Lobby</button>

</div>

<script>
(function() {
    // ----- exact wave logic from first snippet, adapted to lobby page -----
    const path = document.getElementById("wavePath");
    if (!path) return;  // safeguard

   // Change these values in the script section
    const center = 120
    const baseRadius = 105  // Even larger
    const amplitude = 12    // More wave intensity
    const waves = 12
    const points = 180

    let t = 0;
    let rotation = 0;
    const rotationSpeed = 0.01;

    function drawWave() {
        let d = "";
        const pulse = Math.sin(t);          // pulsating amplitude

        for (let i = 0; i <= points; i++) {
            const angle = (i / points) * Math.PI * 2;
            // radius modulated by sine wave around the ring (pulsed)
            const r = baseRadius + amplitude * pulse * Math.sin(waves * angle);

            // apply continuous rotation to whole shape
            const x = center + r * Math.cos(angle + rotation);
            const y = center + r * Math.sin(angle + rotation);

            if (i === 0) {
                d += `M ${x} ${y}`;
            } else {
                d += ` L ${x} ${y}`;
            }
        }
        d += " Z";   // close the loop

        path.setAttribute("d", d);

        t += 0.05;
        rotation += rotationSpeed;

        requestAnimationFrame(drawWave);
    }

    drawWave();

    const path2 = document.getElementById("wavePath"); // same element
    let time = 0;

    function drawWaveCSSrotated() {
        let d = "";
        const pulse = Math.sin(time);   // between -1 and 1

        for (let i = 0; i <= points; i++) {
            const angle = (i / points) * Math.PI * 2;
            const r = baseRadius + amplitude * pulse * Math.sin(waves * angle);

            const x = center + r * Math.cos(angle);
            const y = center + r * Math.sin(angle);

            if (i === 0) d += `M ${x} ${y}`;
            else d += ` L ${x} ${y}`;
        }
        d += " Z";
        path2.setAttribute("d", d);

        time += 0.05;  // speed of pulsing
        requestAnimationFrame(drawWaveCSSrotated);
    }

    drawWaveCSSrotated();

    path2.setAttribute('stroke', 'var(--highlight-color)');
    path2.setAttribute('stroke-width', '4');
    path2.setAttribute('fill', 'none');
})();
</script>

</body>
</html>